console.log('🔧 Configurazione Admin Access');
console.log('');
console.log('📋 ISTRUZIONI PER ACCEDERE COME ADMIN:');
console.log('');
console.log('1. Apri il browser e vai su: http://localhost:3000/admin');
console.log('');
console.log('2. Apri la Console del browser (F12)');
console.log('');
console.log('3. Esegui questo comando nella console:');
console.log('   localStorage.setItem("admin_token", "admin_test_token_123")');
console.log('');
console.log('4. Ricarica la pagina');
console.log('');
console.log('✅ Ora dovresti avere accesso al pannello admin!');
console.log('');
console.log('🔑 Credenziali di test:');
console.log('   - Admin Token: admin_test_token_123');
console.log('');
console.log('📊 Funzionalità disponibili:');
console.log('   - Dashboard con statistiche');
console.log('   - Gestione clienti (CRUD completo)');
console.log('   - Gestione pacchetti (CRUD completo)');
console.log('   - Visualizzazione dati dal database');
console.log('');
console.log('🚀 Per avviare il server: npm run dev'); 